In [31]:
import polars as pl

In [32]:
from pathlib import Path

In [35]:
dataset = Path.cwd().parent.parent / "datasets" / "fifa_performance_dataset" / "fifa_world_cup_2026_player_performance.csv"
df = pl.read_csv(dataset)
df

shape: (54_600, 75)
┌───────────┬───────────┬─────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ player_id ┆ player_na ┆ age ┆ national ┆ … ┆ total_as ┆ total_mi ┆ player_o ┆ tourname │
│ ---       ┆ me        ┆ --- ┆ ity      ┆   ┆ sists_to ┆ nutes_to ┆ f_match_ ┆ nt_ratin │
│ str       ┆ ---       ┆ i64 ┆ ---      ┆   ┆ urnament ┆ urnament ┆ awards   ┆ g        │
│           ┆ str       ┆     ┆ str      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│           ┆           ┆     ┆          ┆   ┆ i64      ┆ i64      ┆ i64      ┆ f64      │
╞═══════════╪═══════════╪═════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ P00055    ┆ Rodri     ┆ 26  ┆ Spanish  ┆ … ┆ 0        ┆ 242      ┆ 0        ┆ 5.8      │
│           ┆ Fati      ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00070    ┆ Ansu Le   ┆ 19  ┆ Spanish  ┆ … ┆ 3        ┆ 342      ┆ 0        ┆ 5.5      │
│           ┆ Normand   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00066    ┆ Gavi      ┆ 18  ┆ Spanish  ┆ … ┆ 1        ┆ 245      ┆ 0        ┆ 8.4      │
│           ┆ Ramos     ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00073    ┆ Pedro     ┆ 20  ┆ Spanish  ┆ … ┆ 3        ┆ 422      ┆ 0        ┆ 6.7      │
│           ┆ Cubarsi   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00059    ┆ Alvaro    ┆ 23  ┆ Spanish  ┆ … ┆ 0        ┆ 440      ┆ 0        ┆ 5.7      │
│           ┆ Oyarzabal ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ …         ┆ …         ┆ …   ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ P00996    ┆ Amir      ┆ 28  ┆ Iraqi    ┆ … ┆ 0        ┆ 97       ┆ 0        ┆ 0.0      │
│           ┆ Younis    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P01006    ┆ Safaa Al- ┆ 20  ┆ Iraqi    ┆ … ┆ 0        ┆ 206      ┆ 0        ┆ 0.0      │
│           ┆ Khafaji   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P01008    ┆ Ahmed     ┆ 26  ┆ Iraqi    ┆ … ┆ 1        ┆ 359      ┆ 0        ┆ 0.0      │
│           ┆ Hussein   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00991    ┆ Ibrahim   ┆ 30  ┆ Iraqi    ┆ … ┆ 0        ┆ 342      ┆ 0        ┆ 0.0      │
│           ┆ Mhawi     ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00989    ┆ Mohannad  ┆ 27  ┆ Iraqi    ┆ … ┆ 0        ┆ 286      ┆ 0        ┆ 0.0      │
│           ┆ Hussein   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
└───────────┴───────────┴─────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [34]:
df.tail(5)

shape: (5, 75)
┌───────────┬───────────┬─────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ player_id ┆ player_na ┆ age ┆ national ┆ … ┆ total_as ┆ total_mi ┆ player_o ┆ tourname │
│ ---       ┆ me        ┆ --- ┆ ity      ┆   ┆ sists_to ┆ nutes_to ┆ f_match_ ┆ nt_ratin │
│ str       ┆ ---       ┆ i64 ┆ ---      ┆   ┆ urnament ┆ urnament ┆ awards   ┆ g        │
│           ┆ str       ┆     ┆ str      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│           ┆           ┆     ┆          ┆   ┆ i64      ┆ i64      ┆ i64      ┆ f64      │
╞═══════════╪═══════════╪═════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ P00996    ┆ Amir      ┆ 28  ┆ Iraqi    ┆ … ┆ 0        ┆ 97       ┆ 0        ┆ 0.0      │
│           ┆ Younis    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P01006    ┆ Safaa Al- ┆ 20  ┆ Iraqi    ┆ … ┆ 0        ┆ 206      ┆ 0        ┆ 0.0      │
│           ┆ Khafaji   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P01008    ┆ Ahmed     ┆ 26  ┆ Iraqi    ┆ … ┆ 1        ┆ 359      ┆ 0        ┆ 0.0      │
│           ┆ Hussein   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00991    ┆ Ibrahim   ┆ 30  ┆ Iraqi    ┆ … ┆ 0        ┆ 342      ┆ 0        ┆ 0.0      │
│           ┆ Mhawi     ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00989    ┆ Mohannad  ┆ 27  ┆ Iraqi    ┆ … ┆ 0        ┆ 286      ┆ 0        ┆ 0.0      │
│           ┆ Hussein   ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
└───────────┴───────────┴─────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [24]:
df['player_id']

shape: (54_600,)
Series: 'player_id' [str]
[
	"P00055"
	"P00070"
	"P00066"
	"P00073"
	"P00059"
	…
	"P00996"
	"P01006"
	"P01008"
	"P00991"
	"P00989"
]

In [45]:
df.filter((pl.col("age")==28) & (pl.col("team") == "France"))

shape: (68, 75)
┌───────────┬───────────┬─────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ player_id ┆ player_na ┆ age ┆ national ┆ … ┆ total_as ┆ total_mi ┆ player_o ┆ tourname │
│ ---       ┆ me        ┆ --- ┆ ity      ┆   ┆ sists_to ┆ nutes_to ┆ f_match_ ┆ nt_ratin │
│ str       ┆ ---       ┆ i64 ┆ ---      ┆   ┆ urnament ┆ urnament ┆ awards   ┆ g        │
│           ┆ str       ┆     ┆ str      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│           ┆           ┆     ┆          ┆   ┆ i64      ┆ i64      ┆ i64      ┆ f64      │
╞═══════════╪═══════════╪═════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ P00014    ┆ Antoine   ┆ 28  ┆ French   ┆ … ┆ 4        ┆ 485      ┆ 0        ┆ 7.3      │
│           ┆ Saliba    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00025    ┆ Eduardo   ┆ 28  ┆ French   ┆ … ┆ 1        ┆ 237      ┆ 0        ┆ 6.1      │
│           ┆ Tchouamen ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│           ┆ i         ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00025    ┆ Eduardo   ┆ 28  ┆ French   ┆ … ┆ 1        ┆ 288      ┆ 0        ┆ 0.0      │
│           ┆ Tchouamen ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│           ┆ i         ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00014    ┆ Antoine   ┆ 28  ┆ French   ┆ … ┆ 0        ┆ 234      ┆ 0        ┆ 0.0      │
│           ┆ Saliba    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00014    ┆ Antoine   ┆ 28  ┆ French   ┆ … ┆ 3        ┆ 357      ┆ 0        ┆ 7.1      │
│           ┆ Saliba    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ …         ┆ …         ┆ …   ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ P00014    ┆ Antoine   ┆ 28  ┆ French   ┆ … ┆ 1        ┆ 383      ┆ 0        ┆ 5.7      │
│           ┆ Saliba    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00025    ┆ Eduardo   ┆ 28  ┆ French   ┆ … ┆ 0        ┆ 109      ┆ 0        ┆ 4.7      │
│           ┆ Tchouamen ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│           ┆ i         ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00014    ┆ Antoine   ┆ 28  ┆ French   ┆ … ┆ 1        ┆ 311      ┆ 0        ┆ 5.7      │
│           ┆ Saliba    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00025    ┆ Eduardo   ┆ 28  ┆ French   ┆ … ┆ 1        ┆ 242      ┆ 0        ┆ 0.0      │
│           ┆ Tchouamen ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│           ┆ i         ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
│ P00014    ┆ Antoine   ┆ 28  ┆ French   ┆ … ┆ 2        ┆ 338      ┆ 0        ┆ 0.0      │
│           ┆ Saliba    ┆     ┆          ┆   ┆          ┆          ┆          ┆          │
└───────────┴───────────┴─────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [51]:
df_avg_height_france = df.filter(pl.col("team")=="France").group_by("team").agg(pl.col("height_cm").mean().alias("Average height"))
df_avg_height_france

shape: (1, 2)
┌────────┬────────────────┐
│ team   ┆ Average height │
│ ---    ┆ ---            │
│ str    ┆ f64            │
╞════════╪════════════════╡
│ France ┆ 182.653846     │
└────────┴────────────────┘

In [52]:
df_avg_height_france = df.group_by("team").alias("Country).agg(pl.col("height_cm").mean().alias("Average height"))
df_avg_height_france

shape: (48, 2)
┌──────────────┬────────────────┐
│ team         ┆ Average height │
│ ---          ┆ ---            │
│ str          ┆ f64            │
╞══════════════╪════════════════╡
│ Spain        ┆ 182.653846     │
│ Peru         ┆ 181.884615     │
│ Netherlands  ┆ 182.692308     │
│ Algeria      ┆ 182.961538     │
│ Italy        ┆ 180.961538     │
│ …            ┆ …              │
│ Saudi Arabia ┆ 180.615385     │
│ Switzerland  ┆ 182.653846     │
│ Japan        ┆ 182.653846     │
│ Portugal     ┆ 180.0          │
│ Mexico       ┆ 181.0          │
└──────────────┴────────────────┘